
ERROR - views - error_logger - 1688 - 5864 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "lexicon_id": "5"}, "event": "lexicon_selection_failed"} - 2016-03-29 15:32:21,540
Traceback (most recent call last):
  File "C:\dev\lexminer\lm\views.py", line 107, in selectLexicon
    dataset = mappings[selected_mapping]['dataset']
NameError: global name 'mappings' is not defined

ERROR - views - error_logger - 1688 - 4940 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "lexicon_id": "54"}, "event": "lexicon_selection_failed"} - 2016-03-29 15:32:28,381
Traceback (most recent call last):
  File "C:\dev\lexminer\lm\views.py", line 107, in selectLexicon
    dataset = mappings[selected_mapping]['dataset']
NameError: global name 'mappings' is not defined

ERROR - views - error_logger - 3776 - 4868 - {"process": "MINE MWEs", "args": {"user_name": "kalamajastaar", "run_id": 13}, "event": "mwe_mining_failed"} - 2016-03-29 15:35:43,683
Traceback (most recent call last):
  File "C:\dev\lexminer\mwe_miner\views.py", line 290, in find_mappings
    raise e
KeyError: 'hits'

ERROR - views - error_logger - 3224 - 5788 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-03-29 16:01:20,641
Traceback (most recent call last):
  File "C:\dev\lexminer\corpus_tool\views.py", line 421, in save
    search = Search(author=request.user,description=desc,dataset=Dataset.get(pk=request.session['dataset']),query=json.dumps(q))
AttributeError: type object 'Dataset' has no attribute 'get'

ERROR - views - error_logger - 3224 - 4272 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-03-29 16:02:49,028
Traceback (most recent call last):
  File "C:\dev\lexminer\corpus_tool\views.py", line 421, in save
    search = Search(author=request.user,description=desc,dataset=Dataset.get(pk=request.session['dataset']),query=json.dumps(q))
AttributeError: type object 'Dataset' has no attribute 'get'

ERROR - views - error_logger - 3520 - 4512 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-03-29 16:08:56,891
Traceback (most recent call last):
  File "C:\dev\lexminer\corpus_tool\views.py", line 421, in save
    search = Search(author=request.user,description=desc,dataset=Dataset.get(pk=request.session['dataset']),query=json.dumps(q))
AttributeError: type object 'Dataset' has no attribute 'get'

ERROR - views - error_logger - 5620 - 2768 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "suggestion_method": "most_similar", "lexicon_id": "64"}, "event": "term_suggestion_failed"} - 2016-04-04 09:43:26,428
Traceback (most recent call last):
  File "C:\dev\lexminer\lm\views.py", line 160, in query
    selected_mapping = int(request.session['mapping'])
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'mapping'

ERROR - views - error_logger - 5620 - 6080 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "suggestion_method": "most_similar", "lexicon_id": "64"}, "event": "term_suggestion_failed"} - 2016-04-04 09:44:05,404
Traceback (most recent call last):
  File "C:\dev\lexminer\lm\views.py", line 160, in query
    selected_mapping = int(request.session['mapping'])
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'mapping'

ERROR - views - error_logger - 6004 - 3524 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:04,789
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 3844 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,028
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 5864 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,043
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 864 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,049
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 6516 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,052
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 3960 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,052
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 172 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,096
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 1000 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,342
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 6564 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,371
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 924 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,381
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 3612 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,381
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 4528 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,382
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 6536 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,408
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 6048 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,654
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 3360 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,687
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 792 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,759
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 5380 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,762
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 6776 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,762
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 3784 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,776
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 4612 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:05,970
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 4616 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:06,017
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 6004 - 3748 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-11 17:40:06,084
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in search2
    q = query2(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 627, in query2
    combined_query["query"]["bool"]["should"].append({"bool":{string_constraint['match_operator']:sub_queries}})
KeyError: 'match_operator'

ERROR - views - error_logger - 436 - 3024 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-18 18:09:40,506
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 368, in save
    q = query(request)
NameError: global name 'query' is not defined

ERROR - views - error_logger - 436 - 4268 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-18 18:09:55,476
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 368, in save
    q = query(request)
NameError: global name 'query' is not defined

ERROR - views - error_logger - 436 - 6900 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-18 18:12:19,565
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 368, in save
    q = query(request)
NameError: global name 'query' is not defined

ERROR - views - error_logger - 6320 - 1172 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-18 18:12:58,661
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 369, in save
    q = query(request)
NameError: global name 'query' is not defined

ERROR - views - error_logger - 728 - 7144 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-18 18:13:46,545
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 368, in save
    q = query2(request)
  File "C:\dev\texta\corpus_tool\views.py", line 545, in query2
    string_constraints[second_part][first_part] = es_params['_'.join(item)]
TypeError: 'WSGIRequest' object has no attribute '__getitem__'

ERROR - views - error_logger - 7048 - 5820 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-19 10:08:26,862
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 369, in save
    desc = request.POST['search_description']
  File "C:\Python27\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'search_description'"

ERROR - views - error_logger - 7048 - 2792 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-19 10:10:23,493
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 368, in save
    q = query2(request)
  File "C:\dev\texta\corpus_tool\views.py", line 545, in query2
    string_constraints[second_part][first_part] = es_params['_'.join(item)]
TypeError: 'WSGIRequest' object has no attribute '__getitem__'

ERROR - views - error_logger - 3776 - 340 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-19 10:14:54,487
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 372, in save
    desc = request.POST['search_description']
  File "C:\Python27\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'search_description'"

ERROR - views - error_logger - 5564 - 1356 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-19 10:15:54,299
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 372, in save
    desc = request.POST['search_description']
  File "C:\Python27\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'search_description'"

ERROR - views - error_logger - 3884 - 5408 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-19 10:27:54,098
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 370, in save
    es_params = {filter_param['name']:filter_param['value'] for filter_param in filter_params}
NameError: global name 'filter_params' is not defined

ERROR - views - error_logger - 5372 - 4772 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-19 10:29:12,203
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 370, in save
    filter_params = json.loads(request.GET['filterParams'])
  File "C:\Python27\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'filterParams'"

ERROR - views - error_logger - 4600 - 6652 - {"process": "SEARCH CORPUS", "args": {"query": {"highlight": {"fields": {"resolutsioon": {"number_of_fragments": 0}}, "post_tags": ["</span>"], "pre_tags": ["<span style='background-color:#FFD119'>"]}, "query": {"bool": {"minimum_should_match": 1, "must": [], "should": [{"bool": {"must": [{"bool": {"minimum_should_match": 1, "should": [{"nested": {"path": "resolutsioon", "query": {"match_phrase": {"resolutsioon.facts": {"query": "tunnistada_s\u00fc\u00fcdi", "slop": "0"}}}}}]}}]}}]}}, "from": "0", "size": "10"}, "user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 12:39:30,157
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 488, in search2
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1732 - 5760 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-04-19 12:59:54,332
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 347, in aggregate
    field_type = response[dataset]['mappings'][mapping]['properties'][aggregation_field]['type']
KeyError: u'kohtu_seisukoht____lemmas'

ERROR - views - error_logger - 1732 - 6492 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-04-19 13:00:11,831
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 347, in aggregate
    field_type = response[dataset]['mappings'][mapping]['properties'][aggregation_field]['type']
KeyError: u'kohus____string'

ERROR - views - error_logger - 5664 - 1424 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "discrete_aggregation_query_failed"} - 2016-04-19 13:05:04,746
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 310, in discrete_agg
    q = query(request)
NameError: global name 'query' is not defined

ERROR - views - error_logger - 5664 - 1424 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-04-19 13:05:04,746
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 356, in aggregate
    data = discrete_agg(request)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\dev\texta\corpus_tool\views.py", line 332, in discrete_agg
    return {'data':[data[0]]+sorted(data[1:], key=lambda x: sum(x[1:]), reverse=True),'height':len(data)*15,'type':'bar','distinct_values':json.dumps(distinct_values)}
UnboundLocalError: local variable 'data' referenced before assignment

ERROR - views - error_logger - 5664 - 1904 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "discrete_aggregation_query_failed"} - 2016-04-19 13:12:47,770
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 310, in discrete_agg
    q = query(request)
NameError: global name 'query' is not defined

ERROR - views - error_logger - 5664 - 1904 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-04-19 13:12:47,770
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 356, in aggregate
    data = discrete_agg(request)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\dev\texta\corpus_tool\views.py", line 332, in discrete_agg
    return {'data':[data[0]]+sorted(data[1:], key=lambda x: sum(x[1:]), reverse=True),'height':len(data)*15,'type':'bar','distinct_values':json.dumps(distinct_values)}
UnboundLocalError: local variable 'data' referenced before assignment

ERROR - views - error_logger - 6948 - 4432 - {"process": "SAVE SEARCH", "args": {"user_name": "kalamajastaar"}, "event": "search_saving_failed"} - 2016-04-19 13:33:45,372
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 146, in save
    q = query2(request)
NameError: global name 'query2' is not defined

ERROR - views - error_logger - 2268 - 4016 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:19,977
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 5156 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:19,993
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 6404 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:19,997
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 4828 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,000
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 4176 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,000
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 6264 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,005
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 2552 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,335
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 6032 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,433
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 5148 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,434
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 4736 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,437
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 4248 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,440
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 3340 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,441
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 844 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,696
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2268 - 6844 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:40:20,755
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 236 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:26,486
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 6632 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:26,730
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 5564 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:26,746
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 2640 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:26,750
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 2852 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:26,753
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 5408 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:26,756
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 3748 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:26,803
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 4172 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:27,288
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 6776 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:27,289
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 5380 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:27,289
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 3052 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:27,292
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 5892 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:27,293
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 580 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:27,329
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5228 - 5816 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:41:28,092
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 373, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 888 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,308
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 4452 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,499
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 6200 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,510
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 5288 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,530
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 1568 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,538
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 4048 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,539
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 6140 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,618
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 2276 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,822
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 3696 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,835
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 1968 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,868
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 1548 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,871
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 5940 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,878
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 3300 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:52,927
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 2932 - 488 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:42:53,138
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 5644 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:44:59,928
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 3564 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,154
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 172 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,158
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 4180 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,164
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 6796 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,167
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 7160 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,170
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 5472 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,250
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 2268 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,562
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 2612 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,575
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 872 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,581
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 3924 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,598
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 236 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,611
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 6920 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,634
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 5260 - 5380 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 14:45:00,917
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 377, in query
    synonym_queries.append({string_constraint['match_type']:{match_field:{match_query}}})
TypeError: unhashable type: 'dict'

ERROR - views - error_logger - 6608 - 5756 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,076
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 2508 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,303
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 6768 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,303
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 4508 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,319
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 4600 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,319
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 3624 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,338
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 1132 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,395
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 2456 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,694
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 5380 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,701
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 7116 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,721
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 6492 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,724
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 2712 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,729
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 6808 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:23,753
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6608 - 6292 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:24,039
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    nynonym_queried.append(nested)
NameError: global name 'nynonym_queried' is not defined

ERROR - views - error_logger - 6660 - 3052 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,410
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 1240 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,638
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 1120 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,638
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 4664 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,638
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 172 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,653
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 5948 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,653
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 4808 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,723
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 3048 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,993
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 1560 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,993
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 5260 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:43,993
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 1824 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:44,026
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 4236 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:44,026
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 6600 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:44,061
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 6660 - 5832 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:44,329
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 247, in search
    q = query(es_params)
  File "C:\dev\texta\corpus_tool\views.py", line 384, in query
    synonym_queried.append(nested)
NameError: global name 'synonym_queried' is not defined

ERROR - views - error_logger - 1392 - 3832 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,293
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 6968 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,474
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 1192 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,474
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 2948 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,497
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 2800 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,502
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 5620 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,509
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 2956 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,707
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 6924 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,868
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 5880 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,875
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 3912 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,885
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 7112 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,894
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 5892 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:57,900
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 1580 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:58,065
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 1392 - 5432 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 15:08:58,242
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 5472 - 6660 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-04-19 16:04:37,326
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 272, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 7540 - 7692 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-04-19 16:31:37,727
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 536, in aggregate
    field_type = response[dataset]['mappings'][mapping]['properties'][aggregation_field]['type']
KeyError: u'text____facts'

ERROR - views - error_logger - 7540 - 948 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-04-19 16:31:51,562
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 536, in aggregate
    field_type = response[dataset]['mappings'][mapping]['properties'][aggregation_field]['type']
KeyError: u'kohus____string'

ERROR - views - error_logger - 996 - 7552 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "discrete_aggregation_query_failed"} - 2016-04-19 16:34:43,960
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 634, in discrete_agg
    normalised_counts,labels = normalise_agg2(response,q,es_params,request,'strings')
NameError: global name 'normalise_agg2' is not defined

ERROR - views - error_logger - 996 - 7552 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-04-19 16:34:43,960
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 545, in aggregate
    data = discrete_agg(es_params,request)
  File "C:\dev\texta\corpus_tool\views.py", line 652, in discrete_agg
    return {'data':[data[0]]+sorted(data[1:], key=lambda x: sum(x[1:]), reverse=True),'height':len(data)*15,'type':'bar','distinct_values':json.dumps(distinct_values)}
UnboundLocalError: local variable 'data' referenced before assignment

ERROR - views - error_logger - 2840 - 3344 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "lexicon_id": "37"}, "event": "lexicon_selection_failed"} - 2016-04-20 16:34:12,401
Traceback (most recent call last):
  File "C:\dev\texta\lm\views.py", line 109, in selectLexicon
    dataset,mapping,date_range = get_active_dataset(request.session['dataset'])
NameError: global name 'get_active_dataset' is not defined

ERROR - views - error_logger - 2840 - 2272 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "lexicon_id": "57"}, "event": "lexicon_selection_failed"} - 2016-04-20 16:34:13,920
Traceback (most recent call last):
  File "C:\dev\texta\lm\views.py", line 109, in selectLexicon
    dataset,mapping,date_range = get_active_dataset(request.session['dataset'])
NameError: global name 'get_active_dataset' is not defined

ERROR - views - error_logger - 2840 - 7132 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "lexicon_id": "5"}, "event": "lexicon_selection_failed"} - 2016-04-20 16:34:20,910
Traceback (most recent call last):
  File "C:\dev\texta\lm\views.py", line 109, in selectLexicon
    dataset,mapping,date_range = get_active_dataset(request.session['dataset'])
NameError: global name 'get_active_dataset' is not defined

ERROR - views - error_logger - 2840 - 7296 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "lexicon_id": "64"}, "event": "lexicon_selection_failed"} - 2016-04-20 16:34:23,006
Traceback (most recent call last):
  File "C:\dev\texta\lm\views.py", line 109, in selectLexicon
    dataset,mapping,date_range = get_active_dataset(request.session['dataset'])
NameError: global name 'get_active_dataset' is not defined

ERROR - views - error_logger - 2840 - 8972 - {"process": "CREATE LEXICON", "args": {"user_name": "kalamajastaar", "lexicon_id": "81"}, "event": "lexicon_selection_failed"} - 2016-04-20 16:34:26,157
Traceback (most recent call last):
  File "C:\dev\texta\lm\views.py", line 109, in selectLexicon
    dataset,mapping,date_range = get_active_dataset(request.session['dataset'])
NameError: global name 'get_active_dataset' is not defined

ERROR - views - error_logger - 7056 - 400 - {"process": "SEARCH CORPUS", "args": {"user_name": ""}, "event": "aggregation_query_failed"} - 2016-05-06 10:19:37,836
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in aggregate
    dataset, mapping, date_range = get_active_dataset(request.session['dataset'])
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'dataset'

ERROR - views - error_logger - 7056 - 5968 - {"process": "SEARCH CORPUS", "args": {"user_name": ""}, "event": "aggregation_query_failed"} - 2016-05-06 10:20:14,359
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 509, in aggregate
    dataset, mapping, date_range = get_active_dataset(request.session['dataset'])
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'dataset'

ERROR - views - error_logger - 6556 - 3956 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:27:46,811
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6556 - 4904 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:27:48,292
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5500 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,029
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 2708 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,395
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5716 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,395
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5292 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,411
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 6544 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,411
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5484 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,433
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 6460 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,490
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 4992 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,733
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5920 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,742
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 2772 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,757
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 6904 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,782
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 1312 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,799
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5788 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:06,818
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5820 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:07,157
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 6612 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:07,157
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 3776 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:07,173
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 7028 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:07,217
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 4952 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:07,217
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 4408 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:07,217
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 2340 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:07,513
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 3444 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,181
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5740 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,509
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 2648 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,509
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 2384 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,536
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 4268 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,536
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 3956 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,536
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5228 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,536
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 3568 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,831
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 3852 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,882
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 4816 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,901
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5636 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,915
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5924 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,931
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 6044 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:12,931
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 5456 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:13,180
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 3840 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:13,213
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 6480 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:13,244
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 3644 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:13,265
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 2972 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:13,267
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 4708 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:13,279
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 2504 - 1136 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 13:31:13,500
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 182, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3772 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:39,648
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 7068 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:39,934
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6848 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:39,934
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6900 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:39,950
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2148 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:39,950
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3928 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:39,960
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6672 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,026
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6280 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,292
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3564 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,296
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4876 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,315
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 832 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,326
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4680 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,346
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5680 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,359
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5368 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,634
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3432 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,750
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4296 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,750
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1488 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,750
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2864 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,765
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2772 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:40,776
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6940 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:03:41,036
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 700 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:20,720
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2184 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,042
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2312 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,056
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1156 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,069
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5820 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,069
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3444 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,072
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 7016 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,111
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 612 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,476
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3992 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,507
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6048 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,509
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5780 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,512
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3524 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,515
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3276 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,543
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5416 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,809
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5912 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,859
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3924 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,885
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3928 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,894
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5380 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,903
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1916 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:21,905
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6832 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:15:22,135
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6968 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:04,859
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5984 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,155
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1440 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,155
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4844 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,155
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1420 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,155
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3264 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,171
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2112 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,207
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2504 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,585
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6192 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,585
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3248 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,601
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6740 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,601
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5400 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,631
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5636 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:05,644
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6356 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:06,019
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4304 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:06,019
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5572 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:06,019
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6488 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:06,040
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5456 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:06,052
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4212 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:06,088
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6444 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:17:06,375
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2952 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,122
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5988 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,371
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6280 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,390
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4756 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,418
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6080 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,426
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2876 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,433
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6900 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,451
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1368 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,700
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 484 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,724
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5752 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,740
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5832 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,805
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6220 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,805
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 7060 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:58,806
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6104 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:59,029
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4940 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:59,052
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4832 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:59,092
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6960 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:59,118
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1876 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:59,134
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6240 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:59,144
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5664 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:25:59,357
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4216 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,361
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4548 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,657
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6760 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,657
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6668 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,657
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5428 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,657
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 7020 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,657
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3864 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,716
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3248 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,980
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2292 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,990
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 700 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:30,996
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 888 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,006
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 400 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,023
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2116 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,052
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4016 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,296
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5544 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,335
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6176 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,335
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4280 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,338
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6048 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,354
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3976 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,375
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3340 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:31,628
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2876 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,112
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1560 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,154
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5512 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,161
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5072 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,167
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2620 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,174
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6220 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,183
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6300 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,423
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3792 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,471
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 7012 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,483
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3224 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,493
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6124 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,507
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4004 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,520
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6924 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,746
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5580 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,783
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6384 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,801
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3028 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,812
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6328 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,822
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2916 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:32,834
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1776 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,085
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2624 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,132
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5716 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,589
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4316 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,601
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2500 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,624
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6768 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,624
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2504 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,624
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3384 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,624
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 1316 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,914
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3588 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,937
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3044 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,963
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5592 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,970
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 4728 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,979
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5752 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:33,996
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3852 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:34,227
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 2620 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:34,255
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 7156 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:34,278
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6220 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:34,293
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 6380 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:34,299
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 5896 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:34,312
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 3460 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:34,575
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 6520 - 240 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:29:34,608
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 273, in search
    es_m.build(es_params)
  File "C:\dev\texta\es_manager\es_manager.py", line 184, in build
    date_range_start = {"range": {date_constraint['daterange_field']: {"gte": date_constraint['daterange_from']}}}
KeyError: 'daterange_from'

ERROR - views - error_logger - 4904 - 484 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "documents_queried"} - 2016-05-11 14:42:55,555
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 293, in search
    out['iTotalRecords'] = response['hits']['total']
KeyError: 'hits'

ERROR - views - error_logger - 300 - 6676 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "discrete_aggregation_query_failed"} - 2016-05-11 17:34:53,190
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 622, in discrete_agg
    normalised_counts,labels = normalise_agg(response, es_m, es_params, 'strings')
  File "C:\dev\texta\corpus_tool\views.py", line 645, in normalise_agg
    raw_counts = [bucket['doc_count'] for bucket in response['aggregations'][agg_type]['buckets']]
KeyError: 'aggregations'

ERROR - views - error_logger - 300 - 6676 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-11 17:34:53,190
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = discrete_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 640, in discrete_agg
    return {'data':[data[0]]+sorted(data[1:], key=lambda x: sum(x[1:]), reverse=True),'height':len(data)*15,'type':'bar','distinct_values':json.dumps(distinct_values)}
UnboundLocalError: local variable 'data' referenced before assignment

ERROR - views - error_logger - 300 - 6708 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "discrete_aggregation_query_failed"} - 2016-05-11 17:34:54,407
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 622, in discrete_agg
    normalised_counts,labels = normalise_agg(response, es_m, es_params, 'strings')
  File "C:\dev\texta\corpus_tool\views.py", line 645, in normalise_agg
    raw_counts = [bucket['doc_count'] for bucket in response['aggregations'][agg_type]['buckets']]
KeyError: 'aggregations'

ERROR - views - error_logger - 300 - 6708 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-11 17:34:54,407
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = discrete_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 640, in discrete_agg
    return {'data':[data[0]]+sorted(data[1:], key=lambda x: sum(x[1:]), reverse=True),'height':len(data)*15,'type':'bar','distinct_values':json.dumps(distinct_values)}
UnboundLocalError: local variable 'data' referenced before assignment

ERROR - views - error_logger - 5572 - 4148 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 14:59:14,101
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 466, in get_facts_from_field
    response = requests.post('http://localhost:9200/_search/scroll?scroll=1m', data=scroll_id).json()
  File "C:\Python27\lib\site-packages\requests\api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /_search/scroll?scroll=1m (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000001CF39A90>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))

ERROR - views - error_logger - 5572 - 3876 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 14:59:47,163
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 466, in get_facts_from_field
    response = requests.post('http://localhost:9200/_search/scroll?scroll=1m', data=scroll_id).json()
  File "C:\Python27\lib\site-packages\requests\api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /_search/scroll?scroll=1m (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000001CF431D0>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))

ERROR - views - error_logger - 5572 - 6720 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:00:09,907
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 466, in get_facts_from_field
    response = requests.post('http://localhost:9200/_search/scroll?scroll=1m', data=scroll_id).json()
  File "C:\Python27\lib\site-packages\requests\api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /_search/scroll?scroll=1m (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000001D0B0A90>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))

ERROR - views - error_logger - 5572 - 4424 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:01:35,795
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 466, in get_facts_from_field
    response = requests.post('http://localhost:9200/_search/scroll?scroll=1m', data=scroll_id).json()
  File "C:\Python27\lib\site-packages\requests\api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /_search/scroll?scroll=1m (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000001D0B8A90>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))

ERROR - views - error_logger - 4820 - 4676 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:06:38,250
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 4820 - 6504 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:07:26,056
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 4820 - 5636 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:07:38,530
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 4820 - 3836 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:08:30,144
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 4820 - 5456 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:08:50,177
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 4820 - 2272 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:09:52,618
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 4820 - 6988 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:10:51,051
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 4820 - 4908 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:12:14,012
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 3012 - 3532 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:17:28,726
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 471, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 6656 - 6080 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:18:16,148
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 471, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 6504 - 6556 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:29:48,503
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - views - error_logger - 6504 - 4980 - {"process": "SEARCH CORPUS", "args": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed"} - 2016-05-18 15:30:04,789
Traceback (most recent call last):
  File "C:\dev\texta\corpus_tool\views.py", line 518, in aggregate
    data = facts_agg(es_params, request)
  File "C:\dev\texta\corpus_tool\views.py", line 616, in facts_agg
    facts = es_m.get_facts_from_field(aggregation_field)
  File "C:\dev\texta\es_manager\es_manager.py", line 470, in get_facts_from_field
    fact = hit['fields']['facts.fact'][0]
KeyError: 'facts.fact'

ERROR - log_manager - error_logger - 6348 - 4380 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "timeline_query_failed", "module": "texta.corpus_tool.views"} - 2016-07-14 12:48:04,190
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 603, in timeline
    normalised_counts,_ = normalise_agg(response, es_m, es_params, 'ranges')
  File "C:\dev\texta\texta\corpus_tool\views.py", line 807, in normalise_agg
    raw_counts = [bucket['doc_count'] for bucket in response['aggregations'][agg_type]['buckets']]
KeyError: 'aggregations'

ERROR - log_manager - error_logger - 6348 - 4380 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed", "module": "texta.corpus_tool.views"} - 2016-07-14 12:48:04,190
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 539, in aggregate
    for i, str_val in enumerate(data['data'][0]):
IndexError: list index out of range

ERROR - log_manager - error_logger - 6236 - 1344 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "documents_queried_failed", "module": "texta.corpus_tool.views"} - 2016-07-14 13:19:27,180
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 383, in search
    link_prefix, link_suffix = es_links[link_key]
ValueError: too many values to unpack

ERROR - log_manager - error_logger - 6236 - 396 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "documents_queried_failed", "module": "texta.corpus_tool.views"} - 2016-07-14 13:19:29,743
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 383, in search
    link_prefix, link_suffix = es_links[link_key]
ValueError: too many values to unpack

ERROR - log_manager - error_logger - 6772 - 5044 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "documents_queried_failed", "module": "texta.corpus_tool.views"} - 2016-07-14 13:19:41,865
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 383, in search
    link_prefix, link_suffix = es_links[link_key]
ValueError: need more than 0 values to unpack

ERROR - log_manager - error_logger - 6772 - 5428 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "documents_queried_failed", "module": "texta.corpus_tool.views"} - 2016-07-14 13:19:49,013
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 383, in search
    link_prefix, link_suffix = es_links[link_key]
ValueError: need more than 0 values to unpack

ERROR - log_manager - error_logger - 2872 - 4060 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "timeline_query_failed", "module": "texta.corpus_tool.views"} - 2016-07-22 12:57:39,308
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 603, in timeline
    normalised_counts,_ = normalise_agg(response, es_m, es_params, 'ranges')
  File "C:\dev\texta\texta\corpus_tool\views.py", line 807, in normalise_agg
    raw_counts = [bucket['doc_count'] for bucket in response['aggregations'][agg_type]['buckets']]
KeyError: 'aggregations'

ERROR - log_manager - error_logger - 2872 - 4060 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed", "module": "texta.corpus_tool.views"} - 2016-07-22 12:57:39,309
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 539, in aggregate
    for i, str_val in enumerate(data['data'][0]):
IndexError: list index out of range

ERROR - log_manager - error_logger - 2872 - 6148 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "documents_queried_failed", "module": "texta.corpus_tool.views"} - 2016-07-22 12:57:46,910
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 320, in search
    for hit in response['hits']['hits']:
KeyError: 'hits'

ERROR - log_manager - error_logger - 3888 - 3792 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "timeline_query_failed", "module": "texta.corpus_tool.views"} - 2016-08-15 19:10:13,502
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 594, in timeline
    normalised_counts,_ = normalise_agg(response, es_m, es_params, 'ranges')
  File "C:\dev\texta\texta\corpus_tool\views.py", line 819, in normalise_agg
    response_all = es_m.search(apply_facts=False)
TypeError: search() got an unexpected keyword argument 'apply_facts'

ERROR - log_manager - error_logger - 3888 - 3792 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed", "module": "texta.corpus_tool.views"} - 2016-08-15 19:10:13,506
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 539, in aggregate
    for i, str_val in enumerate(data['data'][0]):
IndexError: list index out of range

ERROR - log_manager - error_logger - 3888 - 5008 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "timeline_query_failed", "module": "texta.corpus_tool.views"} - 2016-08-15 19:10:18,477
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 594, in timeline
    normalised_counts,_ = normalise_agg(response, es_m, es_params, 'ranges')
  File "C:\dev\texta\texta\corpus_tool\views.py", line 819, in normalise_agg
    response_all = es_m.search(apply_facts=False)
TypeError: search() got an unexpected keyword argument 'apply_facts'

ERROR - log_manager - error_logger - 3888 - 5008 - {"process": "SEARCH CORPUS", "context": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed", "module": "texta.corpus_tool.views"} - 2016-08-15 19:10:18,480
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 539, in aggregate
    for i, str_val in enumerate(data['data'][0]):
IndexError: list index out of range

ERROR - log_manager - error_logger - 4916 - 6940 - {"process": "TIMELINE AGGREGATION", "context": {"user_name": "kalamajastaar"}, "event": "timeline_query_failed", "module": "texta.corpus_tool.views"} - 2016-11-10 10:06:37,637
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 619, in timeline
    normalised_counts,_ = normalise_agg(response, es_m, es_params, 'ranges')
  File "C:\dev\texta\texta\corpus_tool\views.py", line 835, in normalise_agg
    response_all = es_m.search(apply_facts=False)
TypeError: search() got an unexpected keyword argument 'apply_facts'

ERROR - log_manager - error_logger - 4916 - 6940 - {"process": "AGGREGATION", "context": {"user_name": "kalamajastaar"}, "event": "aggregation_query_failed", "module": "texta.corpus_tool.views"} - 2016-11-10 10:06:37,641
Traceback (most recent call last):
  File "C:\dev\texta\texta\corpus_tool\views.py", line 555, in aggregate
    for i, str_val in enumerate(data['data'][0]):
IndexError: list index out of range
